### ISSUE TITLE
Webhooks: create test plan and automate setup

### ISSUE THREAD

**Issue by eladmallel** [livepeer/test-harness#12]
We want to facilitate testing at scale with webhooks in place. This task is about creating a detailed test plan with webhook integration, and automating it as part of the test harness.

Things to consider:
- Does B wait long enough for a response? What does B do if it never receives a response?
- Does B indeed process streams when receiving HTTP 200?
- Does B reject streams when receiving HTTP 4xx?
- Does B emit webhook events as expected? (depends on which events we end up implementing)

Possible useful tool:
- http://httpbin.org/#/Status_codes

**Comment by darkdarkdragon** [comment]
@eladmallel can you please give more details? What do we want test here?

**Comment by eladmallel** [comment]
@darkdarkdragon my thinking was that the person who takes this task will be the person to build the test plan - because it requires some time for thinking ahead, diving into the context of a more detailed spec of the webhooks behavior.

Does this make sense?

**Comment by darkdarkdragon** [comment]
@eladmallel so this is should be tests of webhooks functionality? and `automate setup` refers to automation of tests?

**Comment by eladmallel** [comment]
@darkdarkdragon exactly! now that we understand the task in the same way - what do you think about it?

**Comment by darkdarkdragon** [comment]
@eladmallel we really should define task (webhooks implementation) itself first, and only after start defining tests - we're still discussing what and how to implement in the area of webhooks.
