### ISSUE TITLE
Configure systemd to auto-restart geth if it crashes

### ISSUE THREAD

**Issue by eladmallel** [livepeer/test-harness#15]
Since geth is a SPOF in the M2 architecture, adding this precaution with `systemd` seems like a cost-effective effort.

**Comment by darkdarkdragon** [comment]
as geth is run inside docker, so it is managed by docker. we need to check what docker can offer us in this area.

**Comment by darkdarkdragon** [comment]
I've just checked - if process inside container crashes (checked with geth and livepeer node containers) - docker automatically spin ups new one.

**Comment by hakiran16** [comment]
what if you use terminal (non docker version)
