### ISSUE TITLE
Test with CDN integration

### ISSUE THREAD

**Issue by eladmallel** [livepeer/test-harness#17]
We want to make sure that customers who interact with M2 can successfully hook up a CDN to the network's output. Because there are some issues we're aware of, we want to simulate such a setup ourselves, iron out any obstacles, and end up with clear guidance on how to configure a CDN in front of Livepeer.

### Playlist TTL

The playlist file's TTL/expiration must be shorter than its update rate on origin. So for example, if we are running with one-second segments, the playlist's TTL should be under one second, e.g. 500ms.

### Segments URLs

URLs to segment files: are currently absolute URLs when hooked up to an OS. This doesn't allow us to put a CDN in front of the video. Segment URLs can be one of two
1. Relative paths, in which case the host will be the same host as the playlist, i.e. the CDN.
2. Absolute paths, pointing to the CDN, which means the node would have to be made aware of the CDN (which we're hoping to avoid).

## The task

Setup CloudFlare (or any other CDN) in front of a test network, and configure it such that both the playlist and video files are served successfully through the CDN, ideally without having to change the node to be aware of the CDN.

**Comment by darkdarkdragon** [comment]
- at first we should check Google's CDN offering because we already using Google for serving video.

**Comment by iameli** [comment]
CloudFlare actually specifically forbids hosting video on their CDN - I don't think they'd mind us testing but I'd probably prioritize Google CDN for that reason
