### ISSUE TITLE
Stream Simulator RTMP error

### ISSUE THREAD

**Issue by ya7ya** [livepeer/test-harness#27]
this issue appears in a non deterministic way. but usually when testing with high concurrent stream count. 

here is the [gist of the error](https://gist.github.com/ya7ya/cb8cf202c274a3c349cad3f51fe2947c)

```
av_interleaved_write_frame(): Connection reset by peer 
A      Last message repeated 1 times 
A  [flv @ 0xc84900] Failed to update header with correct duration. 
A  [flv @ 0xc84900] Failed to update header with correct filesize. 
A  Error writing trailer of rtmp://broadcaster_7:1935/stream_2?manifestID=op-BigBuckBunny.mp4-49536292-2: Connection reset by peer 
A  frame=   31 fps=3.2 q=15.0 Lsize=     423kB time=00:00:01.49 bitrate=2321.1kbits/s speed=0.155x     
A  video:423kB audio:19kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown 

```

**Comment by j0sh** [comment]
Recently, I manually tested 20 streams on a single broadcaster and didn't have any issues. How many streams does it typically take to trigger this error?

**Comment by ericxtang** [comment]
Is this still an issue?  cc @ya7ya

**Comment by ya7ya** [comment]
no , I can't seem to reproduce this. we can close it 👍
