### ISSUE TITLE
Generate description of deployment to be sent to customers

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/test-harness#31]
Upon generating new deployment, generate text file with instructions for that deployment.
This should include RTMP ingest endpoints, instructions how to pass stream id and where to find transcoded streams.
This is intended to be sent to user for which this deployment is generated.

**Comment by ya7ya** [comment]
to generate a summary deployment file, you can simply run:

```bash
$ ./test-harness info <deployment_name> > my_summary_file
```
