### ISSUE TITLE
Benchmark: Success Rate with 100 Concurrent Streams 

### ISSUE THREAD

**Issue by ericxtang** [livepeer/test-harness#53]
**Questions to answer**
* What's the highest success rate we can get if we didn't have hardware constraints? (Can we get to 99.999% success rate today?)
* How many Bs, Os & Ts do we need to reach over 99% success rate?  What about 99.9%?  99.99%?
* How does performance degrade as we reduce the number of B, O and T?
* What are the performance bottlenecks?

**Comment by ya7ya** [comment]
** Benchmarking update**

- What's the highest success rate we can get if we didn't have hardware constraints? (Can we get to 99.999% success rate today?)
    - We reached an average of **99.97%** , only 2 out of 15 Bs had a bad success rate (<99%) 

- How many Bs, Os & Ts do we need to reach over 99% success rate? What about 99.9%? 99.99%?
    - 15 Bs, 30 Os (`maxSessions=4`)
    - still testing Multi-T setups
    - GCP setup : 
```js
  machines: {                               
    num: 46,                                
    zone: 'us-east1-b',                     
    machineType: 'n1-highcpu-8',            
    managerMachineType: 'n1-highcpu-8',         
    orchestartorsMachines: 30,              
    broadcastersMachines: 10,               
    broadcasterMachineType: 'n1-highcpu-8', 
    streamerMachineType: 'n1-highcpu-8'     
  },                                        
```

- How does performance degrade as we reduce the number of B, O and T?
     - yes, there is a cyclic behavior that takes down livepeer nodes once we reduce Os to 15 `maxSession=8`

What are the performance bottlenecks?
     - There was a network bottleneck due to the test-harness docker network setup, this was fixed in PR #59.
     - ....
