### ISSUE TITLE
Deploy on AWS with RTMP Proxy

### ISSUE THREAD

**Issue by ericxtang** [livepeer/test-harness#55]
**Setup**
* 2 RTMP proxy nodes + route53 names.
* 2 Bs, each consuming from a different RTMP proxy.
* 3 O/Ts, each connected to both Bs.
* S3 bucket & credential specified for each B

**Questions we want to answer**
* How many concurrent streams (from popular sources on the internet) can this setup handle?
* Can this setup handle RTP?
* Can this setup handle subtitles?
* Can this setup handle timecode?  (For supporting ad insertion)
* Can this setup give us information about the ingest stream? (current bitrate, connection live?, etc)
* Can the Bs serve as the origin for Fastly?
* How much does this cost per month in total?

**Comment by iameli** [comment]
Some initial thoughts...

> Can this setup handle RTP?

Maybe, but as soon as we're talking about UDP protocols there are some postprocessing questions to consider. If we lose some packets, do we buffer that segment?

> Can this setup handle subtitles?

Can our orchestrators and transcoders handle subtitles right now? They'll just have to pass them through but I dunno if we're configured for that sort of thing. Might be blocked on this.

**Comment by ericxtang** [comment]
Done. Closing this issue. Ended up using MediaLive as the RTMP proxy.
