### ISSUE TITLE
Test-harness stops accepting streams after ffmpeg command fails

### ISSUE THREAD

**Issue by angyangie** [livepeer/test-harness#57]
Steps to reproduce the issue:
1. I deploy 27 instances using this [configuration](https://gist.github.com/angyangie/3b1bb0bd7f0dd49a4e0b1454f2f02f10)
2. I run the following ffmpeg command locally, pointed to RTMP port of those instances 

```
ffmpeg -re -i <STREAM_URL> -c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
-c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 
```
3. Stream runs for [730 segments](http://35.231.131.145:3001/d/ZsZv-B3iz/livepeer-overview?orgId=1&from=1557154044828&to=1557154874437), then stops running.

<img width="1680" alt="Screen Shot 2019-05-06 at 11 01 36 AM" src="https://user-images.githubusercontent.com/16169518/57237766-e0298980-6ff5-11e9-9ec8-c6c1655c843b.png">

4. I try running command again. It works. At some point I try running it again, and It gets stuck in stream mapping.

![Screen Shot 2019-05-06 at 11 56 18 AM](https://user-images.githubusercontent.com/16169518/57237806-f9cad100-6ff5-11e9-9f61-405c67f7d60a.png)

5. I simplify command, and only try running one ffmpeg stream at a time. Stream gets stuck. No stream registered in Grafana. 
```
ffmpeg -re -i <STREAM_URL> -c:v copy -c:a aac -f flv  rtmp://35.196.6.230:2524 \
```

6.  I try streaming to RTMP port using OBS. Stream gets stuck. No stream registered in Grafana.

7. I stop and start instances using the GC console interface. Still can't stream anything to instances. I have to remove them and run `node examples/multigroups.js` again to restart instances from terminal

**Comment by angyangie** [comment]
**Console logs:**

**angie@angie-instance-1:~$** ffmpeg -re -i  https://video-weaver.jfk04.hls
.ttvnw.net/v1/playlist/CsoDmTTh1-wpn-FdVECd35Juas8CopzQabCzNM_LV710uKiZ
ALssf1M-91xwo7cuwu0HuxbvYTvwtfn5tqVQm4i7N_eLZN6qNv-wPBnxriwXPf-f4GbB8MF
SCLtZM8P5jJfQ8q3qrxKUKpB5pDg8faaSL0doXEionVE-rOiEj237q_Do6vNSgSBppUMMEp
OdsdGJfX34cp4kD7XaHs5VXYNFTi_9L_fQYO6p7oRDzBJNa2Q3O47DQoNqveZv8uB-8lfD8
-VX9A7xgA6CHy3QuzBEP-9WBdxukkfPMWyBwfj_gzjEv9yTEvaR6O5qCa4JTi6BmcaGZPpc
PSWNl4j4ites2IOHQoAFbdyCLw8r7iPcjViohDKsVPA_vaa8F_O9x_L6IIz5k76t3kzwBUu
Z0E44g3Zt1jaxmP6shWvs7frTJCKOz8x-92WW4LlxEf_63SBnM-hTpYm_Sn7pPgeDo484Jy
DrIIfVdpwdcKNfwohiVrUTSY_w4djAoLKGIJJxX76CUyYWRREWsI4x7ZHCZOYvI7FcTnUyk
llzMDDwoSKLTFsLhZU_KAnrrbledCggTPtSka5E05HptMaun24RqMzyxMy7wAvAMBWBgW0S
ECzCwNeFr9kY81ORsioGrP8aDInjJLou1ubbEsQfdA.m3u8 -c:v copy -c:a aac -f f
lv -strict -2  rtmp://35.243.141.70:2641 
ffmpeg version 3.2.12-1~deb9u1 Copyright (c) 2000-2018 the FFmpeg devel
opers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --prefix=/usr --extra-version='1~deb9u1' --toolchain=h
ardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64

-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enabl
e-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-lib
bluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libe
bur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --
enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame -
-enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpu
lse --enable-librubberband --enable-libshine --enable-libsnappy --enabl
e-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable
-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --en
able-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable
-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --e
nable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei
0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
[hls,applehttp @ 0x558583cc2f20] Opening 'https://video-edge-ee7128.jfk
04.abs.hls.ttvnw.net/v1/segment/Cs4D3xXtP50w4GJctBMdaxYFckMYH2z4zZ7KeC2
_3B9Bxi9WeTAzBlYQ5teh13jWo4iixwGDw_zy8oqmGnLjJBLvMw8l7f-GOpFB9HTgskqeNV
_PvSaOqsLPWa2IF3iAmtftWYQyJw59INNIBp3BMWh2V3BFGsPyPNSTjhXb4OU0-pI2yfK3m
KFbLvnO08N2zNOXIhLZugm_ClNRYbALiCLdQ8-MU-JiKHOopEezIp7stYiEQqO_k61uytkm
ZdDGuLUjDnBC3Akv2f_vmZ2bXt_lYxV_YI65NOvSKDOMs803tk_t8lpoz8ybBakXgMtfSZb
0svoF7xAw6vjTefuUD7hGulSibqChxuVapKdlYV3QhS9euhQxcWOyCQobsycsjYKp0hiK8Q
P6b2-rZu-_vbIkXR7u8A6a6Ty9ewmzVCYD0pU_LH5ft91css2Pu50uxJHrEwPGDB66a3pvn
yiiOd6MJWn9-sQOGFU17RL4TqTlNVl3CJNv1-C9c0KP6-GoMvTXzX5JlAcTPvtTgCo1Fvgg
uy9G-nWgDHW3Sn_Io7L3-QkcZamidN3zL0P3qN81u3nePaxUiPBUQxIQ4cNhY49uHUkH4PQ
bKjONN1g_fecjEhDFDPFE6y1fWHXbB249Ly1fGgykccJ5mps9RAmxMqM.ts' for readin
g
Input #0, hls,applehttp, from 'https://video-weaver.jfk04.hls.ttvnw.net
/v1/playlist/CsoDmTTh1-wpn-FdVECd35Juas8CopzQabCzNM_LV710uKiZALssf1M-91
xwo7cuwu0HuxbvYTvwtfn5tqVQm4i7N_eLZN6qNv-wPBnxriwXPf-f4GbB8MFSCLtZM8P5j
JfQ8q3qrxKUKpB5pDg8faaSL0doXEionVE-rOiEj237q_Do6vNSgSBppUMMEpOdsdGJfX34
cp4kD7XaHs5VXYNFTi_9L_fQYO6p7oRDzBJNa2Q3O47DQoNqveZv8uB-8lfD8-VX9A7xgA6
CHy3QuzBEP-9WBdxukkfPMWyBwfj_gzjEv9yTEvaR6O5qCa4JTi6BmcaGZPpcPSWNl4j4it
es2IOHQoAFbdyCLw8r7iPcjViohDKsVPA_vaa8F_O9x_L6IIz5k76t3kzwBUuZ0E44g3Zt1
jaxmP6shWvs7frTJCKOz8x-92WW4LlxEf_63SBnM-hTpYm_Sn7pPgeDo484JyDrIIfVdpwd
cKNfwohiVrUTSY_w4djAoLKGIJJxX76CUyYWRREWsI4x7ZHCZOYvI7FcTnUykllzMDDwoSK
LTFsLhZU_KAnrrbledCggTPtSka5E05HptMaun24RqMzyxMy7wAvAMBWBgW0SECzCwNeFr9
kY81ORsioGrP8aDInjJLou1ubbEsQfdA.m3u8':
  Duration: N/A, start: 16812.316000, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, st
ereo, fltp
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 
1920x1080, 60 tbr, 90k tbn, 120 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 0
Output #0, flv, to 'rtmp://35.243.141.70:2641':
  Metadata:
    encoder         : Lavf57.56.101
    Stream #0:0: Video: h264 (High) ([7][0][0][0] / 0x0007), yuv420p, 1
920x1080, q=2-31, 60 tbr, 1k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([10][0][0][0] / 0x000A), 44100 Hz, st
ereo, fltp, 128 kb/s
    Metadata:
      variant_bitrate : 0
      encoder         : Lavc57.64.101 aac
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help

**Comment by j0sh** [comment]
Not sure if this is a copy-paste issue but there were some linebreaks in the input URL, I was able to get ffplay playback with the input URL:

```
https://video-edge-ee7128.jfk04.abs.hls.ttvnw.net/v1/segment/Cs4DYtyVAKsnO160uOrdLJP16A6DHtQgwaq3d_NpRRCnQEq0K4YTbqGV3G3f92qr_ceKR7zwU4LniXGbDANuoFs--bh2DkpZ54lMRss7Th8iHb9f9zMqx-iJAlcEPjhjZVi_2tE9vIjwxPNuksGRddmHWzKP6XCirD4LHVBDdvHgDW3VWvaYPnYR33KSbXFy2VD3XJMpy-GUkRconm1T1Q0d4aNYezCCEmsCCfdyXV-I9nL6fNlLTVUZxYsSm1uFX58j8anXU5RAZVoe2UAn0sTu3McPFjzZYE51VkUramY7c7QeKt1PGFyWHO8EreXtdfHm_zJFZOwVAKZODeBesWUf68eSMNCh8RmkDwja06uNScWJCnJPKkgKX1VXBdLhayi78Aswfab90IPjHUsx1p1s9I20Uq3R3yi_G6DilGwitNdG2K_uZu3BVwjEmjK1_atsEIZ-TVHjQfauWZERzkNZhX6BVPZr1u2qx-iG8byyR_iG-zVrsIXlN-Tt1lNPUAQkzaiXOfIqm4MBnQbaJEG10VH8VIHckv3BB8qZKPXC2utJbsGMd0LBypOvd6WIHjfcgBX8BT5YloRITvW-x_-fv5urpMyrdDaXf0nS_YBOEhDXVWyhh-aUrhYRojvOzFYJGgxV3hGuA7JQ__-k2MY.ts
```

This is what I get when trying to relay the stream using a similar command as yours:

```
ffmpeg -re -i  https://video-edge-ee7128.jfk04.abs.hls.ttvnw.net/v1/segment/Cs4DYtyVAKsnO160uOrdLJP16A6DHtQgwaq3d_NpRRCnQEq0K4YTbqGV3G3f92qr_ceKR7zwU4LniXGbDANuoFs--bh2DkpZ54lMRss7Th8iHb9f9zMqx-iJAlcEPjhjZVi_2tE9vIjwxPNuksGRddmHWzKP6XCirD4LHVBDdvHgDW3VWvaYPnYR33KSbXFy2VD3XJMpy-GUkRconm1T1Q0d4aNYezCCEmsCCfdyXV-I9nL6fNlLTVUZxYsSm1uFX58j8anXU5RAZVoe2UAn0sTu3McPFjzZYE51VkUramY7c7QeKt1PGFyWHO8EreXtdfHm_zJFZOwVAKZODeBesWUf68eSMNCh8RmkDwja06uNScWJCnJPKkgKX1VXBdLhayi78Aswfab90IPjHUsx1p1s9I20Uq3R3yi_G6DilGwitNdG2K_uZu3BVwjEmjK1_atsEIZ-TVHjQfauWZERzkNZhX6BVPZr1u2qx-iG8byyR_iG-zVrsIXlN-Tt1lNPUAQkzaiXOfIqm4MBnQbaJEG10VH8VIHckv3BB8qZKPXC2utJbsGMd0LBypOvd6WIHjfcgBX8BT5YloRITvW-x_-fv5urpMyrdDaXf0nS_YBOEhDXVWyhh-aUrhYRojvOzFYJGgxV3hGuA7JQ__-k2MY.ts -c:a copy -c:v copy -f flv rtmp://35.243.141.70:2641
ffmpeg version n4.0-5-ga768c0a3e1 Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 10.0.0 (clang-1000.11.45.5)
  configuration: --prefix=/Users/josh/Livepeer/node/compiled --enable-libx264 --enable-gpl --enable-shared --disable-static
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, mpegts, from 'https://video-edge-ee7128.jfk04.abs.hls.ttvnw.net/v1/segment/Cs4DYtyVAKsnO160uOrdLJP16A6DHtQgwaq3d_NpRRCnQEq0K4YTbqGV3G3f92qr_ceKR7zwU4LniXGbDANuoFs--bh2DkpZ54lMRss7Th8iHb9f9zMqx-iJAlcEPjhjZVi_2tE9vIjwxPNuksGRddmHWzKP6XCirD4LHVBDdvHgDW3VWvaYPnYR33KSbXFy2VD3XJMpy-GUkRconm1T1Q0d4aNYezCCEmsCCfdyXV-I9nL6fNlLTVUZxYsSm1uFX58j8anXU5RAZVoe2UAn0sTu3McPFjzZYE51VkUramY7c7QeKt1PGFyWHO8EreXtdfHm_zJFZOwVAKZODeBesWUf68eSMNCh8RmkDwja06uNScWJCnJPKkgKX1VXBdLhayi78Aswfab90IPjHUsx1p1s9I20Uq3R3yi_G6DilGwitNdG2K_uZu3BVwjEmjK1_atsEIZ-TVHjQfauWZERzkNZhX6BVPZr1u2qx-iG8byyR_iG-zVrsIXlN-Tt1lNPUAQkzaiXOfIqm4MBnQbaJEG10VH8VIHckv3BB8qZKPXC2utJbsGMd0LBypOvd6WIHjfcgBX8BT5YloRITvW-x_-fv5urpMyrdDaXf0nS_YBOEhDXVWyhh-aUrhYRojvOzFYJGgxV3hGuA7JQ__-k2MY.ts':
  Duration: 00:00:01.87, start: 17444.499000, bitrate: 8418 kb/s
  Program 1 
    Stream #0:0[0x100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 150 kb/s
    Stream #0:1[0x101]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1920x1080, 60 fps, 60 tbr, 90k tbn, 120 tbc
    Stream #0:2[0x102]: Data: timed_id3 (ID3  / 0x20334449)
[rtmp @ 0x7ffc34c0dc00] Cannot open connection tcp://35.243.141.70:2641
rtmp://35.243.141.70:2641: Operation timed out
```

Is the `35.243.141.70` server up and the network port open? Can't ping it.

**Comment by angyangie** [comment]
Ah yes, definitely a copy and paste issue on this issue. I pasted the same command into the terminal for cases when B received the streams just fine, and for cases when it didn't. Great observation though!

**Comment by j0sh** [comment]
Isn't this fixed with the resolution of https://github.com/livepeer/go-livepeer/issues/843 ?
