### ISSUE TITLE
Use test harness to spin up a demo env for 5 concurrent streams

### ISSUE THREAD

**Issue by eladmallel** [livepeer/test-harness#7]
To make sure we are ready to demo Livepeer on-demand, we want to spin up a cloud setup that can support at least 5 concurrent streams. This involves:

1. Configuring test harness for this need (probably pushing a stable configuration to this repo for fast reuse)
2. Spinning up a test network
3. Testing 5 concurrent streams on it, making sure all streams are transcoding with the required success rate
4. Verifying that we can easily spin up networks with 1xB,O as well as 2xB,O

**Comment by darkdarkdragon** [comment]
PR with config is [here](https://github.com/livepeer/test-harness/pull/30)
